name: Ma2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    needs: [build, approval]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        with:
          environment: production

  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request approval
        uses: peter-evans/approval-action@v2.1.0
        with:
          token: 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
          message: "Please approve this deployment to production."
          reviewers: "Gaurav9969351313"